"""
PyGitUp Git Hooks Management
===========================
Tools to install and manage Git hooks for automatic security scanning.
"""

import os
import sys
import stat
import subprocess
from .ui import print_success, print_error, print_info, print_warning, print_header

HOOK_TEMPLATE = f"""#!/usr/bin/env python3
# PyGitUp Pre-Commit Security Hook
# Automatically generated by PyGitUp

import os
import sys
import subprocess

def run_scan():
    print("🛡️ PyGitUp: Running pre-commit security scan...")
    
    # Get staged files
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True, text=True, check=True
        )
        staged_files = result.stdout.strip().split('\\n')
        staged_files = [f for f in staged_files if f]
        
        if not staged_files:
            return True
            
        # Run PyGitUp security scan in non-interactive mode
        # We use sys.executable to ensure we use the same python environment
        cmd = [sys.executable, "-m", "pygitup.main", "--mode", "security-scan", "--path", "."]
        
        # Check if we should only scan staged files (future enhancement)
        # For now, we scan the whole directory but focusing on staged files is better
        
        env = os.environ.copy()
        env["PYGITUP_NON_INTERACTIVE"] = "1"
        
        # Run the scan
        scan_result = subprocess.run(cmd, env=env)
        
        if scan_result.returncode != 0:
            print("\\n❌ [bold red]SECURITY CHECK FAILED[/bold red]")
            print("PyGitUp detected potential security issues in your changes.")
            print("Please review the findings above and fix them before committing.")
            print("To bypass this check (NOT RECOMMENDED), use: git commit --no-verify")
            return False
            
        print("✅ PyGitUp: Security scan passed.")
        return True
    except Exception as e:
        print(f"⚠️ PyGitUp: Hook execution error: {{e}}")
        # On error, we allow the commit but warn the user
        return True

if __name__ == "__main__":
    if not run_scan():
        sys.exit(1)
    sys.exit(0)
"""

def install_pre_commit_hook():
    """Install the PyGitUp pre-commit hook in the current repository."""
    print_header("Git Hook Installation")
    
    # Check if in a git repo
    if not os.path.isdir(".git"):
        print_error("Not a git repository. Cannot install hooks.")
        return False
    
    hook_path = os.path.join(".git", "hooks", "pre-commit")
    
    if os.path.exists(hook_path):
        print_warning(f"A pre-commit hook already exists at {hook_path}")
        choice = input("Would you like to overwrite it or append to it? (o/a/c): ").lower()
        if choice == 'c':
            return False
        elif choice == 'a':
            try:
                with open(hook_path, 'a') as f:
                    f.write("\n\n# Added by PyGitUp\n")
                    f.write(f"{sys.executable} -m pygitup.main --mode security-scan --path .\n")
                print_success("PyGitUp scan appended to existing hook.")
                return True
            except Exception as e:
                print_error(f"Failed to append hook: {e}")
                return False
            
    try:
        with open(hook_path, 'w') as f:
            f.write(HOOK_TEMPLATE)
            
        # Make it executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        
        print_success("PyGitUp pre-commit hook installed successfully!")
        print_info("Your commits will now be automatically scanned for secrets and vulnerabilities.")
        return True
    except Exception as e:
        print_error(f"Failed to install hook: {e}")
        return False

def uninstall_pre_commit_hook():
    """Remove the PyGitUp pre-commit hook."""
    hook_path = os.path.join(".git", "hooks", "pre-commit")
    
    if not os.path.exists(hook_path):
        print_info("No pre-commit hook found.")
        return True
        
    try:
        # Check if it's ours
        with open(hook_path, 'r') as f:
            content = f.read()
            if "PyGitUp Pre-Commit Security Hook" not in content:
                print_warning("The existing pre-commit hook was not created by PyGitUp.")
                confirm = input("Are you sure you want to delete it? (y/n): ").lower()
                if confirm != 'y':
                    return False
        
        os.remove(hook_path)
        print_success("Pre-commit hook uninstalled.")
        return True
    except Exception as e:
        print_error(f"Failed to uninstall hook: {e}")
        return False
